# ============================================================
# 1. Namespace
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: kube-system
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-external-eso
  namespace: petclinic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: petclinic-db-eso
    creationPolicy: Owner
    template:
        data:
          SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .DB_HOST }}:3306/petclinic?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
          SPRING_DATASOURCE_USERNAME: "{{ .DB_USER }}"
          SPRING_DATASOURCE_PASSWORD: "{{ .DB_PASS }}"
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: petclinic/db-connection-info
        property: host
    - secretKey: DB_USER
      remoteRef:
        key: rds!db-c1186c24-a3f0-4309-82a2-18f1a3623a82
        property: username
    - secretKey: DB_PASS
      remoteRef:
        key: rds!db-c1186c24-a3f0-4309-82a2-18f1a3623a82
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-secret-eso
  namespace: petclinic
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: ai-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: ai-secret
        property: API_KEY
