name: YAML Validate CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  yaml-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install and Run Kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/
          
          echo "=== .github 폴더를 제외한 순수 YAML 파일만 골라서 검사 시작 ==="
          
          # 1. find 명령어로 .github 폴더는 완전히 배제(-prune)하고, 확장자가 yaml/yml인 파일만 찾습니다.
          # 2. 찾은 파일 목록을 kubeconform에 한 번에 넘겨서 검사합니다.
          find . -path "./.github" -prune -o -name "*.yaml" -o -name "*.yml" -print0 | xargs -0 kubeconform -summary -ignore-missing-schemas
