name: YAML Validate CI

on:
  push:
    branches: ["main", "develop"]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  pull_request:
    branches: ["main", "develop"]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  yaml-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install and Run Kubeconform
        run: |
          curl -L -o kubeconform.tar.gz https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz
          tar -xzf kubeconform.tar.gz
          sudo mv kubeconform /usr/local/bin/
          
          # -reject 옵션에 정규식을 사용하여 .github 파일이 들어오면 무조건 거부(Reject)합니다.
          kubeconform -summary -ignore-missing-schemas -reject '.*\.github.*' .
